name: Run test for mytools

env:
  target: .

on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/test-mytools.yml'
  push:
    branches: main
    paths:
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/test-mytools.yml'
  schedule:
    - cron:  '00 21 * * 5'
  workflow_dispatch:

defaults:
  run:
    working-directory: .

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up PHP 8.2
      uses: shivammathur/setup-php@v2
      with:
        php-version: "8.2"
        extensions: grpc

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Get current directory
      id: current_dir
      run: echo "CURRENT_DIR=$(pwd)" >> $GITHUB_OUTPUT

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v4
      with:
        path: ${{ steps.current_dir.outputs.CURRENT_DIR }}/vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Create tests/configs/*.json
      env:
        DECODED_GPT_BASE64: ${{ secrets.GPT_BASE64 }}
        DECODED_LINE_BASE64: ${{ secrets.LINE_BASE64 }}
      run: |
        mkdir -p ${{ env.target }}/tests/configs \
        && echo $DECODED_GPT_BASE64 | base64 --decode > tests/configs/gpt.json \
        && echo $DECODED_LINE_BASE64 | base64 --decode > tests/configs/line.json

    - name: Test with phpunit
      run: bash tests/run_tests.sh
